
package tictactoe.core;

public enum  ViewController{
MAINVIEWCONTROLLER,
ONLINEMULTIPLAYERVIEWCONTROLLER,
MENUDIALOGCONTROLLER,
WINNERDIALOGCNTROLLER,
AVAILABLEPLAYERSVIEWCONTROLLER,
SINGLEPLAYERVIEWCONTROLLER,
MULTIPLAYERVIEWCONTROLLER,
REGISTRATIONVIEWCONTROLLER,
LOGINVIEWCONTROLLER, 
SINGLEMODEVIEWCONTROLLER,
MULTIMODEVIEWCONTROLLER,
MULTIPLAYERWINNERDIALOG,
 SINGLEWINNERDIALOGCONTROLLER,
 EXITDIALOGCONTROLLER
}
