
package tictactoe.core;

public enum  ViewController{
MAINVIEWCONTROLLER,
ONLINEVIEWCONTROLLER,
MENUDIALOGCONTROLLER,
WINNERDIALOGCNTROLLER,
AVAILABLEPLAYERSVIEWCONTROLLER,
SINGLEVIEWCONTROLLER,
MULTIVIEWCONTROLLER,
REGISTRATIONVIEWCONTROLLER,
LOGINVIEWCONTROLLER, 
SINGLEMODEVIEWCONTROLLER,
MULTIMODEVIEWCONTROLLER
}